/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRecordedRouteImport } from './routes/_authenticated/recorded'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings.route'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedNotionWebhooksRouteImport } from './routes/_authenticated/notion/webhooks'
import { Route as AuthenticatedNotionCallbackRouteImport } from './routes/_authenticated/notion/callback'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecordedRoute = AuthenticatedRecordedRouteImport.update({
  id: '/recorded',
  path: '/recorded',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedNotionWebhooksRoute =
  AuthenticatedNotionWebhooksRouteImport.update({
    id: '/notion/webhooks',
    path: '/notion/webhooks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotionCallbackRoute =
  AuthenticatedNotionCallbackRouteImport.update({
    id: '/notion/callback',
    path: '/notion/callback',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/recorded': typeof AuthenticatedRecordedRoute
  '/notion/callback': typeof AuthenticatedNotionCallbackRoute
  '/notion/webhooks': typeof AuthenticatedNotionWebhooksRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/recorded': typeof AuthenticatedRecordedRoute
  '/notion/callback': typeof AuthenticatedNotionCallbackRoute
  '/notion/webhooks': typeof AuthenticatedNotionWebhooksRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/recorded': typeof AuthenticatedRecordedRoute
  '/_authenticated/notion/callback': typeof AuthenticatedNotionCallbackRoute
  '/_authenticated/notion/webhooks': typeof AuthenticatedNotionWebhooksRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/recorded'
    | '/notion/callback'
    | '/notion/webhooks'
    | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/recorded'
    | '/notion/callback'
    | '/notion/webhooks'
    | '/settings/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/_authenticated/recorded'
    | '/_authenticated/notion/callback'
    | '/_authenticated/notion/webhooks'
    | '/_authenticated/settings/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recorded': {
      id: '/_authenticated/recorded'
      path: '/recorded'
      fullPath: '/recorded'
      preLoaderRoute: typeof AuthenticatedRecordedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/notion/webhooks': {
      id: '/_authenticated/notion/webhooks'
      path: '/notion/webhooks'
      fullPath: '/notion/webhooks'
      preLoaderRoute: typeof AuthenticatedNotionWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notion/callback': {
      id: '/_authenticated/notion/callback'
      path: '/notion/callback'
      fullPath: '/notion/callback'
      preLoaderRoute: typeof AuthenticatedNotionCallbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedRecordedRoute: typeof AuthenticatedRecordedRoute
  AuthenticatedNotionCallbackRoute: typeof AuthenticatedNotionCallbackRoute
  AuthenticatedNotionWebhooksRoute: typeof AuthenticatedNotionWebhooksRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedRecordedRoute: AuthenticatedRecordedRoute,
  AuthenticatedNotionCallbackRoute: AuthenticatedNotionCallbackRoute,
  AuthenticatedNotionWebhooksRoute: AuthenticatedNotionWebhooksRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
